"""End-to-end Omega_GW(f) regression against validated reference spectra.

Each reference spectrum in tests/test_data/reference/ was generated by
scripts/generate_reference_spectra.py from the paper parameters and *validated*
against the independent numpy/scipy oracle (see MANIFEST.md); these tests:

1. recompute Omega_GW(f) through the canonical OmegaGW model (built by
   _sigway_configs.build_model) and require it to reproduce the stored spectrum
   to rtol 1e-4 -- deterministic recompute matches to ~1e-6, so 1e-4 leaves
   head-room for benign FP reordering while still failing on any >=0.01% physics
   change (a 5% shift fails by 500x);
2. re-assert the stored oracle-validation error is within its documented
   tolerance, so the fixture can never become an unvalidated snapshot.

This is the primary safety net for the refactor: it targets the public
Omega_GW-given-config surface, not internal helpers.
"""

import os
import json

import numpy as np
import jax.numpy as jnp
import pytest

import _sigway_configs as C

REFDIR = os.path.join(os.path.dirname(__file__), "test_data", "reference")

_ALL = ["bpl_rd", "lognormal_rd", "osc_multifield_rd", "emd_imd2rd", "usr_ms"]


def _f_and_params(name):
    cfg = C.USR_CONFIG if name == "usr_ms" else C.ANALYTIC_CONFIGS[name]
    return jnp.array(cfg["f"]), cfg["params"]


@pytest.mark.parametrize("name", _ALL)
def test_regression(name):
    """OmegaGW(build_model) reproduces the validated reference spectrum."""
    ref = np.load(os.path.join(REFDIR, f"{name}.npz"))
    model = C.build_model(name)
    f, params = _f_and_params(name)
    got = np.array(model(f, *params))
    peak = np.nanmax(ref["omega_gw"])
    np.testing.assert_allclose(
        got, ref["omega_gw"], rtol=1e-4, atol=peak * 1e-10
    )


@pytest.mark.parametrize("name", _ALL)
def test_fixture_is_validated(name):
    """The stored spectrum's oracle-validation error is within its tolerance."""
    d = np.load(os.path.join(REFDIR, f"{name}.npz"))
    meta = json.loads(str(d["meta"]))
    assert meta["max_relerr"] < meta["tol"]
