"""End-to-end Omega_GW(f) regression against validated reference spectra.

Each reference spectrum in tests/test_data/reference/ was generated by
scripts/generate_reference_spectra.py from the paper parameters and *validated*
against the independent numpy/scipy oracle (see MANIFEST.md); these tests:

1. recompute Omega_GW(f) from the same single-source-of-truth config and require
   it to reproduce the stored spectrum to rtol 1e-4 -- deterministic recompute
   matches to ~1e-6, so 1e-4 leaves head-room for benign FP reordering during
   the refactor while still failing on any >=0.01% physics change (a 5% shift
   fails by 500x);
2. re-assert the stored oracle-validation error is within its documented
   tolerance, so the fixture can never become an unvalidated snapshot.

This is the primary safety net for the planned refactor: it targets the public
Omega_GW-given-config surface, not internal helpers.
"""
import os
import json

import numpy as np
import jax.numpy as jnp
import pytest

from sigway.omega_gw_jax import OmegaGWjax
from sigway.ms_solver import SingleFieldSolver
from sigway.omega_gw_ms import OmegaGWms
import _sigway_configs as C

REFDIR = os.path.join(os.path.dirname(__file__), "test_data", "reference")


def _load(name):
    d = np.load(os.path.join(REFDIR, f"{name}.npz"))
    meta = json.loads(str(d["meta"]))
    return d, meta


def _build_analytic(name):
    cfg = C.ANALYTIC_CONFIGS[name]
    m = OmegaGWjax(
        cfg["pzeta"], jnp.array(cfg["s"]), cfg["t"], f=jnp.array(cfg["f"]),
        norm=cfg["norm"], kernel=cfg["kernel"], upsample=True,
        dP_zeta="auto", jit=True,
    )
    return np.array(m(jnp.array(cfg["f"]), *cfg["params"]))


@pytest.mark.parametrize(
    "name", ["bpl_rd", "lognormal_rd", "osc_multifield_rd", "emd_imd2rd"]
)
def test_analytic_regression(name):
    """Recomputed analytic-P_zeta spectrum reproduces the validated fixture."""
    ref, meta = _load(name)
    got = _build_analytic(name)
    peak = np.nanmax(ref["omega_gw"])
    np.testing.assert_allclose(
        got, ref["omega_gw"], rtol=1e-4, atol=peak * 1e-10
    )


@pytest.mark.parametrize(
    "name",
    ["bpl_rd", "lognormal_rd", "osc_multifield_rd", "emd_imd2rd", "usr_ms"],
)
def test_fixture_is_validated(name):
    """The stored spectrum's oracle-validation error is within its tolerance."""
    _, meta = _load(name)
    assert meta["max_relerr"] < meta["tol"]


def test_usr_ms_regression():
    """Recomputed Mukhanov-Sasaki (USR) spectrum reproduces the fixture."""
    ref, meta = _load("usr_ms")
    cfg = C.USR_CONFIG
    solver = SingleFieldSolver(
        C.usr_potential, phi0=cfg["phi0"], pi0=cfg["pi0"],
        N_CMB_to_end=cfg["N_CMB_to_end"], k=jnp.array(cfg["k_solver"]),
    )
    t = C.usr_t_grid(nf=len(cfg["f"]))
    integ = OmegaGWms(
        solver, jnp.array(cfg["s"]), t, f=jnp.array(cfg["f"]),
        kernel=cfg["kernel"], upsample=True,
    )
    got = np.array(integ(jnp.array(cfg["f"]), *cfg["params"]))
    peak = np.nanmax(ref["omega_gw"])
    np.testing.assert_allclose(
        got, ref["omega_gw"], rtol=1e-4, atol=peak * 1e-10
    )
